export const ACCOUNT_UPGRADED_SUCCESSFULLY = "ACCOUNT_UPGRADED_SUCCESSFULLY";
export const ACCOUNT_UPGRADED_UNSUCCESSFULLY = "ACCOUNT_UPGRADED_UNSUCCESSFULLY";
export const HIDE_ACCOUNT_UPGRADED_NOTIFICATION = "HIDE_ACCOUNT_UPGRADED_NOTIFICATION";

export const hideAccountUpgradedNotification = () => {
  return {type: HIDE_ACCOUNT_UPGRADED_NOTIFICATION};
}