export const MESSAGE_SENT_SUCCESSFULLY = "MESSAGE_SENT_SUCCESSFULLY";
export const MESSAGE_SENT_UNSUCCESSFULLY = "MESSAGE_SENT_UNSUCCESSFULLY";
export const HIDE_MESSAGE_SENT_NOTIFICATION = "HIDE_MESSAGE_SENT_NOTIFICATION";

export const hideMessageSentNotification = () => {
  return {type: HIDE_MESSAGE_SENT_NOTIFICATION};
}