export const GALLERY_IMAGE_UPLOADED_SUCCESSFULLY = "GALLERY_IMAGE_UPLOADED_SUCCESSFULLY";
export const GALLERY_IMAGE_UPLOADED_UNSUCCESSFULLY = "GALLERY_IMAGE_UPLOADED_UNSUCCESSFULLY";
export const HIDE_GALLERY_IMAGE_UPLOADED_NOTIFICATION = "HIDE_GALLERY_IMAGE_UPLOADED_NOTIFICATION";

export const GALLERY_IMAGE_DELETED_SUCCESSFULLY = "GALLERY_IMAGE_DELETED_SUCCESSFULLY";
export const GALLERY_IMAGE_DELETED_UNSUCCESSFULLY = "GALLERY_IMAGE_DELETED_UNSUCCESSFULLY";
export const HIDE_GALLERY_IMAGE_DELETED_NOTIFICATION = "HIDE_GALLERY_IMAGE_DELETED_NOTIFICATION";

export const hideGalleryImageUploadedNotification = () => {
  return {type: HIDE_GALLERY_IMAGE_UPLOADED_NOTIFICATION};
}

export const hideGalleryImageDeletedNotification = () => {
  return {type: HIDE_GALLERY_IMAGE_DELETED_NOTIFICATION};
}