export const HUSTLR_CARD_REVIEWS_FETCHED_SUCCESSFULLY =
  "HUSTLR_CARD_REVIEWS_FETCHED_SUCCESSFULLY";
export const HUSTLR_CARD_REVIEWS_FETCHED_UNSUCCESSFULLY =
  "HUSTLR_CARD_REVIEWS_FETCHED_UNSUCCESSFULLY";
export const HIDE_HUSTLR_CARD_REVIEWS_FETCHED_NOTIFICATION =
  "HIDE_HUSTLR_CARD_REVIEWS_FETCHED_NOTIFICATION";

export const HUSTLR_CARD_REVIEW_FETCHED_SUCCESSFULLY =
  "HUSTLR_CARD_REVIEW_FETCHED_SUCCESSFULLY";
export const HUSTLR_CARD_REVIEW_FETCHED_UNSUCCESSFULLY =
  "HUSTLR_CARD_REVIEW_FETCHED_UNSUCCESSFULLY";
export const HIDE_HUSTLR_CARD_REVIEW_FETCHED_NOTIFICATION =
  "HIDE_HUSTLR_CARD_REVIEW_FETCHED_NOTIFICATION";

export const HUSTLR_CARD_REVIEW_CREATED_SUCCESSFULLY =
  "HUSTLR_CARD_REVIEW_CREATED_SUCCESSFULLY";
export const HUSTLR_CARD_REVIEW_CREATED_UNSUCCESSFULLY =
  "HUSTLR_CARD_REVIEW_CREATED_UNSUCCESSFULLY";
export const HIDE_HUSTLR_CARD_REVIEW_CREATED_NOTIFICATION =
  "HIDE_HUSTLR_CARD_REVIEW_CREATED_NOTIFICATION";

export const HUSTLR_CARD_REVIEW_SAVED_SUCCESSFULLY =
  "HUSTLR_CARD_REVIEW_SAVED_SUCCESSFULLY";
export const HUSTLR_CARD_REVIEW_SAVED_UNSUCCESSFULLY =
  "HUSTLR_CARD_REVIEW_SAVED_UNSUCCESSFULLY";
export const HIDE_HUSTLR_CARD_REVIEW_SAVED_NOTIFICATION =
  "HIDE_HUSTLR_CARD_REVIEW_SAVED_NOTIFICATION";

export const HUSTLR_CARD_REVIEW_DELETED_SUCCESSFULLY =
  "HUSTLR_CARD_REVIEW_DELETED_SUCCESSFULLY";
export const HUSTLR_CARD_REVIEW_DELETED_UNSUCCESSFULLY =
  "HUSTLR_CARD_REVIEW_DELETED_UNSUCCESSFULLY";
export const HIDE_HUSTLR_CARD_REVIEW_DELETED_NOTIFICATION =
  "HIDE_HUSTLR_CARD_REVIEW_DELETED_NOTIFICATION";

export const HUSTLR_CARD_REVIEW_PHOTO_DELETED_SUCCESSFULLY =
  "HUSTLR_CARD_REVIEW_PHOTO_DELETE_SUCCESSFULLY";
export const HUSTLR_CARD_REVIEW_PHOTO_DELETED_UNSUCCESSFULLY =
  "HUSTLR_CARD_REVIEW_PHOTO_DELETED_UNSUCCESSFULLY";
export const HIDE_HUSTLR_CARD_REVIEW_PHOTO_DELETED_NOTIFICATION =
  "HIDE_HUSTLR_CARD_REVIEW_PHOTO_DELETED_NOTIFICATION";

export const hideHustlrCardReviewsFetchedNotification = () => {
  return { type: HIDE_HUSTLR_CARD_REVIEWS_FETCHED_NOTIFICATION };
};

export const hideHustlrCardReviewFetchedNotification = () => {
  return { type: HIDE_HUSTLR_CARD_REVIEW_FETCHED_NOTIFICATION };
};

export const hideHustlrCardReviewCreatedNotification = () => {
  return { type: HIDE_HUSTLR_CARD_REVIEW_CREATED_NOTIFICATION };
};

export const hideHustlrCardReviewSavedNotification = () => {
  return { type: HIDE_HUSTLR_CARD_REVIEW_SAVED_NOTIFICATION };
};

export const hideHustlrCardReviewDeletedNotification = () => {
  return { type: HIDE_HUSTLR_CARD_REVIEW_DELETED_NOTIFICATION };
};

export const hideHustlrCardReviewPhotoDeletedNotification = () => {
  return { type: HIDE_HUSTLR_CARD_REVIEW_PHOTO_DELETED_NOTIFICATION };
};
