export const OFFERING_CREATED_SUCCESSFULLY = "OFFERING_CREATED_SUCCESSFULLY";
export const OFFERING_CREATED_UNSUCCESSFULLY =
  "OFFERING_CREATED_UNSUCCESSFULLY";
export const HIDE_OFFERING_CREATED_NOTIFICATION =
  "HIDE_OFFERING_CREATED_NOTIFICATION";

export const OFFERING_SAVED_SUCCESSFULLY = "OFFERING_SAVED_SUCCESSFULLY";
export const OFFERING_SAVED_UNSUCCESSFULLY = "OFFERING_SAVED_UNSUCCESSFULLY";
export const HIDE_OFFERING_SAVED_NOTIFICATION =
  "HIDE_OFFERING_SAVED_NOTIFICATION";

export const OFFERING_DELETED_SUCCESSFULLY = "OFFERING_DELETED_SUCCESSFULLY";
export const OFFERING_DELETED_UNSUCCESSFULLY =
  "OFFERING_DELETED_UNSUCCESSFULLY";
export const HIDE_OFFERING_DELETED_NOTIFICATION =
  "HIDE_OFFERING_DELETED_NOTIFICATION";

export const hideOfferingCreatedNotification = () => {
  return { type: HIDE_OFFERING_CREATED_NOTIFICATION };
};

export const hideOfferingSavedNotification = () => {
  return { type: HIDE_OFFERING_SAVED_NOTIFICATION };
};

export const hideOfferingDeletedNotification = () => {
  return { type: HIDE_OFFERING_DELETED_NOTIFICATION };
};
