export const OFFERING_IMAGE_UPLOADED_SUCCESSFULLY = "OFFERING_IMAGE_UPLOADED_SUCCESSFULLY";
export const OFFERING_IMAGE_UPLOADED_UNSUCCESSFULLY = "OFFERING_IMAGE_UPLOADED_UNSUCCESSFULLY";
export const HIDE_OFFERING_IMAGE_UPLOADED_NOTIFICATION = "HIDE_OFFERING_IMAGE_UPLOADED_NOTIFICATION";

export const OFFERING_IMAGE_DELETED_SUCCESSFULLY = "OFFERING_IMAGE_DELETED_SUCCESSFULLY";
export const OFFERING_IMAGE_DELETED_UNSUCCESSFULLY = "OFFERING_IMAGE_DELETED_UNSUCCESSFULLY";
export const HIDE_OFFERING_IMAGE_DELETED_NOTIFICATION = "HIDE_OFFERING_IMAGE_DELETED_NOTIFICATION";

export const hideOfferingImageUploadedNotification = () => {
  return {type: HIDE_OFFERING_IMAGE_UPLOADED_NOTIFICATION};
}

export const hideOfferingImageDeletedNotification = () => {
  return {type: HIDE_OFFERING_IMAGE_DELETED_NOTIFICATION};
}