export const PROFILE_IMAGE_UPLOADED_SUCCESSFULLY = "PROFILE_IMAGE_UPLOADED_SUCCESSFULLY";
export const PROFILE_IMAGE_UPLOADED_UNSUCCESSFULLY = "PROFILE_IMAGE_UPLOADED_UNSUCCESSFULLY";
export const HIDE_PROFILE_IMAGE_UPLOADED_NOTIFICATION = "HIDE_PROFILE_IMAGE_UPLOADED_NOTIFICATION";

export const PROFILE_IMAGE_DELETED_SUCCESSFULLY = "PROFILE_IMAGE_DELETED_SUCCESSFULLY";
export const PROFILE_IMAGE_DELETED_UNSUCCESSFULLY = "PROFILE_IMAGE_DELETED_UNSUCCESSFULLY";
export const HIDE_PROFILE_IMAGE_DELETED_NOTIFICATION = "HIDE_PROFILE_IMAGE_DELETED_NOTIFICATION";

export const hideProfileImageUploadedNotification = () => {
  return {type: HIDE_PROFILE_IMAGE_UPLOADED_NOTIFICATION};
}

export const hideProfileImageDeletedNotification = () => {
  return {type: HIDE_PROFILE_IMAGE_DELETED_NOTIFICATION};
}