export const LINK_CREATED_SUCCESSFULLY = "LINK_CREATED_SUCCESSFULLY";
export const LINK_CREATED_UNSUCCESSFULLY = "LINK_CREATED_UNSUCCESSFULLY";
export const HIDE_LINK_CREATED_NOTIFICATION = "HIDE_LINK_CREATED_NOTIFICATION";

export const LINK_SAVED_SUCCESSFULLY = "LINK_SAVED_SUCCESSFULLY";
export const LINK_SAVED_UNSUCCESSFULLY = "LINK_SAVED_UNSUCCESSFULLY";
export const HIDE_LINK_SAVED_NOTIFICATION = "HIDE_LINK_SAVED_NOTIFICATION";

export const LINK_DELETED_SUCCESSFULLY = "LINK_DELETED_SUCCESSFULLY";
export const LINK_DELETED_UNSUCCESSFULLY = "LINK_DELETED_UNSUCCESSFULLY";
export const HIDE_LINK_DELETED_NOTIFICATION = "HIDE_LINK_DELETED_NOTIFICATION";

export const hideLinkCreatedNotification = () => {
  return {type: HIDE_LINK_CREATED_NOTIFICATION};
}

export const hideLinkSavedNotification = () => {
  return {type: HIDE_LINK_SAVED_NOTIFICATION};
}

export const hideLinkDeletedNotification = () => {
  return {type: HIDE_LINK_DELETED_NOTIFICATION};
}