export const REQUEST_TIMEOUT_ERR = "REQUEST_TIMEOUT_ERR";
export const INVALID_LOGIN_CREDENTIALS_ERR = "INVALID_LOGIN_CREDENTIALS_ERR";
export const INVALID_REGISTER_CREDENTIALS_ERR =
  "INVALID_REGISTER_CREDENTIALS_ERR";
export const TAKEN_REGISTER_USERNAME_EMAIL_ERR =
  "TAKEN_REGISTER_USERNAME_EMAIL_ERR";
export const INVALID_REGISTER_EMAIL_PASSWORD_ERR =
  "INVALID_REGISTER_EMAIL_PASSWORD_ERR";
export const NOT_MATCH_REGISTER_PASSWORDS_ERR =
  "NOT_MATCH_REGISTER_PASSWORDS_ERR";
export const NO_LOGIN_ERRORS = "NO_LOGIN_ERRORS";
export const NO_REGISTER_ERRORS = "NO_REGISTER_ERRORS";
