export const REQUEST_TIMEOUT_ERR = "REQUEST_TIMEOUT_ERR";
export const INVALID_LOGIN_CREDENTIALS_ERR = "INVALID_LOGIN_CREDENTIALS_ERR";
export const INVALID_REGISTER_CREDENTIALS_ERR =
  "INVALID_REGISTER_CREDENTIALS_ERR";
export const NO_LOGIN_ERRORS = "NO_LOGIN_ERRORS";
