export const formFields = {
  cardPath: "PathToCard",
  cardEmail: "Email",
  cardDescription: "Description",
  offeringTitle: "Title",
  personalInfoUsername: "Username",
  personalInfoEmail: "Email",
  changePasswordCurrentPassword: "OldPassword",
  changePasswordNewPassword: "NewPassword",
  changePasswordConfirmPassword: "ConfirmPassword",
  registerEmail: "Email",
  registerUsername: "Username",
  registerPassword: "Password",
  registerConfirmPassword: "ConfirmPassword",
  forgotPasswordUsername: "Username",
  changePasswordCodeUsername: "Username",
  changePasswordCodeCode: "RecoveryCode",
  changePasswordCodeNewPassword: "NewPassword",
};
