export const SET_CHANGE_PASSWORD_CODE_AUTH_ERROR =
  "SET_CHANGE_PASSWORD_CODE_AUTH_ERROR";
export const REMOVE_CHANGE_PASSWORD_CODE_AUTH_ERROR =
  "REMOVE_CHANGE_PASSWORD_CODE_AUTH_ERROR";

export const clearChangePasswordCodeAuthError = () => {
  return {
    type: REMOVE_CHANGE_PASSWORD_CODE_AUTH_ERROR,
  };
};
