export const HUSTLR_CARD_REVIEWS_ARE_LOADING =
  "HUSTLR_CARD_REVIEWS_ARE_LOADING";
export const HUSTLR_CARD_REVIEWS_ARE_NOT_LOADING =
  "HUSTLR_CARD_REVIEWS_ARE_NOT_LOADING";

export const HUSTLR_CARD_NEXT_REVIEWS_ARE_LOADING =
  "HUSTLR_CARD_NEXT_REVIEWS_ARE_LOADING";
export const HUSTLR_CARD_NEXT_REVIEWS_ARE_NOT_LOADING =
  "HUSTLR_CARD_NEXT_REVIEWS_ARE_NOT_LOADING";

export const HUSTLR_CARD_REVIEW_IS_LOADING = "HUSTLR_CARD_REVIEW_IS_LOADING";
export const HUSTLR_CARD_REVIEW_IS_NOT_LOADING =
  "HUSTLR_CARD_REVIEW_IS_NOT_LOADING";

export const HUSTLR_CARD_REVIEW_IS_CREATING_LOADER =
  "HUSTLR_CARD_REVIEW_IS_CREATING_LOADER";
export const HUSTLR_CARD_REVIEW_IS_NOT_CREATING_LOADER =
  "HUSTLR_CARD_REVIEW_IS_NOT_CREATING_LOADER";

export const HUSTLR_CARD_REVIEW_IS_UPDATING_LOADER =
  "HUSTLR_CARD_REVIEW_IS_UPDATING_LOADER";
export const HUSTLR_CARD_REVIEW_IS_NOT_UPDATING_LOADER =
  "HUSTLR_CARD_REVIEW_IS_NOT_UPDATING_LOADER";

export const HUSTLR_CARD_REVIEW_IS_DELETING_LOADER =
  "HUSTLR_CARD_REVIEW_IS_DELETING_LOADER";
export const HUSTLR_CARD_REVIEW_IS_NOT_DELETING_LOADER =
  "HUSTLR_CARD_REVIEW_IS_NOT_DELETING_LOADER";

export const HUSTLR_CARD_REVIEW_PHOTO_IS_DELETING_LOADER =
  "HUSTLR_CARD_REVIEW_PHOTO_IS_DELETING_LOADER";
export const HUSTLR_CARD_REVIEW_PHOTO_IS_NOT_DELETING_LOADER =
  "HUSTLR_CARD_REVIEW_PHOTO_IS_NOT_DELETING_LOADER";

export const HUSTLR_CARD_REVIEW_LIKE_IS_LOADING =
  "HUSTLR_CARD_REVIEW_LIKE_IS_LOADING";
export const HUSTLR_CARD_REVIEW_LIKE_IS_NOT_LOADING =
  "HUSTLR_CARD_REVIEW_LIKE_IS_NOT_LOADING";
