export const OFFERING_IS_CREATING_LOADER = "OFFERING_IS_CREATING_LOADER";
export const OFFERING_IS_NOT_CREATING_LOADER = "OFFERING_IS_NOT_CREATING_LOADER";

export const OFFERING_IS_DELETING_LOADER = "OFFERING_IS_DELETING_LOADER";
export const OFFERING_IS_NOT_DELETING_LOADER = "OFFERING_IS_NOT_DELETING_LOADER";