export const LINK_IS_CREATING_LOADER = "LINK_IS_CREATING_LOADER";
export const LINK_IS_NOT_CREATING_LOADER = "LINK_IS_NOT_CREATING_LOADER";

export const LINK_IS_UPDATING_LOADER = "LINK_IS_UPDATING_LOADER";
export const LINK_IS_NOT_UPDATING_LOADER = "LINK_IS_NOT_UPDATING_LOADER";

export const LINK_IS_DELETING_LOADER = "LINK_IS_DELETING_LOADER";
export const LINK_IS_NOT_DELETING_LOADER = "LINK_IS_NOT_DELETING_LOADER";