export const SET_CHANGE_PASSWORD_CODE_VALIDATION_ERRORS =
  "SET_CHANGE_PASSWORD_CODE_VALIDATION_ERRORS";
export const REMOVE_CHANGE_PASSWORD_CODE_VALIDATION_ERRORS =
  "REMOVE_CHANGE_PASSWORD_CODE_VALIDATION_ERRORS";

export const clearChangePasswordCodeValidationErrors = () => {
  return {
    type: REMOVE_CHANGE_PASSWORD_CODE_VALIDATION_ERRORS,
  };
};
